Update the error handling. (#29)
This allows to go from an error message to look like this:

```
thread 'main' (9280059) panicked at src/api.rs:183:14:
Failed to read .env file: Io(Custom { kind: NotFound, error: "path not found" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

To an error message that looks like this:

```
Error: Failed to load necessary environment variables

Caused by:
    0: Failed to read .env file
    1: path not found
    2: path not found
```

Now the load_env function does not report a useful error and maybe
it should be handled differently. But this is not the point of this PR.